spring:
  datasource:
    url: jdbc:mysql://221.163.53.82:9000/community_db
    username: tina
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  aws:
    credentials:
      access-key: AKIA6ODU3AUSNGYJL5PL
      secret-key: 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